### ISSUE TITLE
Many thanks for the repo and for the notes

### ISSUE THREAD

**Issue by vlsi** [Quuxplusone/BugzillaToGithub#1]
There will be Apache JMeter migration from https://bz.apache.org/bugzilla to GitHub issues, so the scripts and notes are really helpful.

I really like that you separate export vs transform vs import steps.

**Comment by Quuxplusone** [comment]
You're very welcome! I also wrote [a blog post](https://quuxplusone.github.io/blog/2021/12/11/llvm-bugzilla-fan-edit/), which I should link to from the README here.

**Comment by vlsi** [comment]
I figured out the repository from the blog post 👍 

It might probably make sense to link interesting findings from the migration.
For example, Bugzilla -> Gitlab -> GitHub sounds clever as one can spawn temporary Gitlab instances that are not rate-limited.

**Comment by vlsi** [comment]
I ended up with using Bugzilla database directly rather than scraping the Bugzilla UI.

Here's my migration script:
https://github.com/vlsi/bugzilla2github
